name: CreateTestRelease

on:
   workflow_dispatch:
     inputs:
       release:
         description: Release number
         required: true
         type: string
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[release]"
      - name: Fake version number
        run: |
          echo "__version__ = \"${{ github.event.inputs.RELEASE }}\"" > src/infra_surveyor/__init__.py
      - name: Build Distribution
        run: |
          flit build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/